### ISSUE TITLE
本地启动访问报错

### ISSUE THREAD

**Issue by lidada-qd** [Dafeigy/ChartsGPT#4]
![image](https://github.com/Dafeigy/ChartsGPT/assets/66238476/bfdf0cc1-1d37-4fb8-8721-dfc2a764ec59)
![image](https://github.com/Dafeigy/ChartsGPT/assets/66238476/2ccc4940-f150-4f8c-bd0e-3fc4ad63db89)

**Comment by Dafeigy** [comment]
你好，控制台的log显示状态码为304，这是Flask中的一个常见的问题。请尝试**清除浏览器缓存**，随后重新运行`app.py`。在您正确配置`config.json`后，应该能正常使用。

**Comment by Dafeigy** [comment]
我重新复现了这个问题，该问题是由于返回内容的解析部分。我在最新的提交`commit 3b62b2f528c50de2d9c71f8f5e1fa2f61c7823b9` 中暂时抛弃了内容解析的功能，因为目前GPT的返回内容正如Prompt的指示，此时应该能正常使用。我会在本月稍晚一点的时候修复一下这个bug。:)
